### Add user to database

POST http://localhost:3000/users/addUser
Content-Type: application/json

{
    "user":"test-user",
    "password":"test-password"
}


### Get all users

GET http://localhost:3000/users/

### Get specified user

GET http://localhost:3000/users/3


### Delete specified user

DELETE http://localhost:3000/users/1


### Delete all users
DELETE http://localhost:3000/users


### Update specified user

PUT http://localhost:3000/users/3
Content-Type: application/json

{
    "user" : "updated user",
    "password" : "updated password"
}